dt = 0.1;
t = 0:dt:100;
t_now = zeros(size(t));
x0 = zeros(size(t));
y0 = zeros(size(t));
z0 = zeros(size(t));
q0 = zeros(size(t));
q1 = zeros(size(t));
q2 = zeros(size(t));
q3 = zeros(size(t));
theta1 = zeros(size(t));
theta2 = zeros(size(t));
theta3 = zeros(size(t));
theta4 = zeros(size(t));
theta5 = zeros(size(t));
vx0 = zeros(size(t));
vy0 = zeros(size(t));
vz0 = zeros(size(t));
wx0 = zeros(size(t));
wy0 = zeros(size(t));
wz0 = zeros(size(t));
dtheta1 = zeros(size(t));
dtheta2 = zeros(size(t));
dtheta3 = zeros(size(t));
dtheta4 = zeros(size(t));
dtheta5 = zeros(size(t));
control1 = zeros(size(t));
control2 = zeros(size(t));
control3 = zeros(size(t));
control4 = zeros(size(t));
control5 = zeros(size(t));
control6 = zeros(size(t));
control7 = zeros(size(t));
control8 = zeros(size(t));
control9 = zeros(size(t));
control10 = zeros(size(t));
control11 = zeros(size(t));
t_now(1) = 0.0;
q0(1) = 1.0;
q1(1) = 0.0;
q2(1) = 0.0;
q3(1) = 0.0;
x0(1) = 0.0;
y0(1) = 0.0;
z0(1) = 0.0;
theta1(1) = 2;
theta2(1) = 2;
theta3(1) = 2;
theta4(1) = 2;
theta5(1) = 2;
wx0(1) = 0.0;
wy0(1) = 0.0;
wz0(1) = 0.0;
vx0(1) = 0.0;
vy0(1) = 0.0;
vz0(1) = 0.0;
dtheta1(1) = 0.0;
dtheta2(1) = 0.0;
dtheta3(1) = 0.0;
dtheta4(1) = 0.0;
dtheta5(1) = 0.0;
control1(1) = 0.0;
control2(1) = 0.0;
control3(1) = 0.0;
control4(1) = 0.0;
control5(1) = 0.0;
control6(1) = 0.0;
control7(1) = 0.0;
control8(1) = 0.0;
control9(1) = 0.0;
control10(1) = 0.0;
control11(1) = 0.0;

for i = 2:length(t)
    state = [q0(i-1); q1(i-1); q2(i-1); q3(i-1); x0(i-1); y0(i-1); z0(i-1); theta1(i-1); theta2(i-1); theta3(i-1); theta4(i-1); theta5(i-1); wx0(i-1); wy0(i-1); wz0(i-1); vx0(i-1); vy0(i-1); vz0(i-1); dtheta1(i-1); dtheta2(i-1); dtheta3(i-1); dtheta4(i-1); dtheta5(i-1)];
    u = control(state,t_now(i-1));
    next_state = runge_kutta_step(@system_dynamics, t_now(i-1), state, u, dt);
    t_now(i) = t_now(i-1) + dt;
    q0(i)=next_state(1);
    q1(i)=next_state(2); 
    q2(i)=next_state(3); 
    q3(i)=next_state(4); 
    x0(i)=next_state(5); 
    y0(i)=next_state(6);  
    z0(i)=next_state(7);  
    theta1(i)=next_state(8);  
    theta2(i)=next_state(9);  
    theta3(i)=next_state(10);  
    theta4(i)=next_state(11);  
    theta5(i)=next_state(12);  
    wx0(i)=next_state(13);  
    wy0(i)=next_state(14);  
    wz0(i)=next_state(15);  
    vx0(i)=next_state(16);  
    vy0(i)=next_state(17);  
    vz0(i)=next_state(18); 
    dtheta1(i)=next_state(19);  
    dtheta2(i)=next_state(20);  
    dtheta3(i)=next_state(21);  
    dtheta4(i)=next_state(22);  
    dtheta5(i)=next_state(23);  
    control1(i)=u(1);
    control2(i)=u(2); 
    control3(i)=u(3); 
    control4(i)=u(4); 
    control5(i)=u(5); 
    control6(i)=u(6);
    control7(i)=u(7); 
    control8(i)=u(8); 
    control9(i)=u(9); 
    control10(i)=u(10); 
    control11(i)=u(11); 

    disp(t_now(i-1));
end

% 绘制结果图形
figure;
plot(t, wx0, 'LineWidth', 1.5);
hold on;
plot(t, wy0, 'LineWidth', 1.5);
plot(t, wz0, 'LineWidth', 1.5);
xlabel('Time');
ylabel('Value');
title('角速度');
legend('wx','wy','wz');
grid on;
hold off;

figure;
plot(t, vx0, 'LineWidth', 1.5);
hold on;
plot(t, vy0, 'LineWidth', 1.5);
plot(t, vz0, 'LineWidth', 1.5);
xlabel('Time');
ylabel('Value');
title('速度');
legend('vx','vy','vz');
grid on;
hold off;

figure;
plot(t, q0, 'LineWidth', 1.5);
hold on;
plot(t, q1, 'LineWidth', 1.5);
plot(t, q2, 'LineWidth', 1.5);
plot(t, q3, 'LineWidth', 1.5);
xlabel('Time');
ylabel('Value');
title('本体姿态');
legend('q0','q1','q2','q3');
grid on;
hold off;

figure;
plot(t, x0, 'LineWidth', 1.5);
hold on;
plot(t, y0, 'LineWidth', 1.5);
plot(t, z0, 'LineWidth', 1.5);
xlabel('Time');
ylabel('Value');
title('本体质心位置');
legend('x0','y0','z0');
grid on;
hold off;

figure;
plot(t, theta1, 'LineWidth', 1.5);
hold on;
plot(t, theta2, 'LineWidth', 1.5);
plot(t, theta3, 'LineWidth', 1.5);
plot(t, theta4, 'LineWidth', 1.5);
plot(t, theta5, 'LineWidth', 1.5);
xlabel('Time');
ylabel('Value');
title('关节角');
legend('theta1','theta2','theta3','theta4','theta5');
grid on;
hold off;
